# Generated by Django 4.0.3 on 2022-03-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
    ]
