# Generated by Django 4.0.4 on 2022-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Name',
            field=models.CharField(default='Juanen', max_length=20),
            preserve_default=False,
        ),
    ]
