# Generated by Django 4.0.3 on 2022-04-23 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0002_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_ini', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('fecha_fin', models.DateField(default=django.utils.datetime_safe.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupied', models.BooleanField()),
                ('description', models.CharField(max_length=200)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
            ],
        ),
    ]
