# Generated by Django 4.0.3 on 2022-03-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0002_rename_admins_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EventsAndMore.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='EventsAndMore.user'),
            preserve_default=False,
        ),
    ]
