# Generated by Django 4.0.3 on 2022-04-25 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0002_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_ini', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('fecha_fin', models.DateField(default=django.utils.datetime_safe.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeticionStand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('estado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('clientUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente')),
                ('gestorUsername', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.gestor')),
                ('idEvento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occupied', models.BooleanField()),
                ('description', models.CharField(max_length=200)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
            ],
        ),
        migrations.CreateModel(
            name='StandIncidence',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(max_length=200)),
                ('Date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('Status', models.BooleanField(default=False, editable=False)),
                ('Checked', models.BooleanField(default=False, editable=False)),
                ('Client_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente')),
                ('Current_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
                ('Gestor_Username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.gestor')),
                ('Stand_Incidenced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.stand')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='webuser',
            name='is_gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peticionstand',
            name='idStand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.stand'),
        ),
    ]
