# Generated by Django 4.0.4 on 2022-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0003_event_gestor_peticionstand_stand_standincidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standincidence',
            name='Checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='standincidence',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
