# Generated by Django 4.0.4 on 2022-04-23 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0003_remove_staff_id_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Date_Init', models.DateField(default=datetime.date.today)),
                ('Date_End', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Occupied', models.BooleanField()),
                ('Description', models.CharField(max_length=200)),
                ('Current_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
            ],
        ),
        migrations.CreateModel(
            name='StandRequest',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Status', models.BooleanField(default=False, editable=False)),
                ('Checked', models.BooleanField(default=False, editable=False)),
                ('Client_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente')),
                ('Current_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
                ('Gestor_Username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.gestor')),
                ('Stand_Requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.stand')),
            ],
        ),
        migrations.CreateModel(
            name='StandIncidence',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(max_length=200)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Status', models.BooleanField(default=False, editable=False)),
                ('Checked', models.BooleanField(default=False, editable=False)),
                ('Client_Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente')),
                ('Current_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
                ('Gestor_Username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.gestor')),
                ('Stand_Incidenced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.stand')),
            ],
        ),
    ]
