# Generated by Django 4.0.4 on 2022-04-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0004_event_gestor_stand_standrequest_standincidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
                ('Id_Stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.stand')),
            ],
        ),
    ]
