# Generated by Django 4.0.3 on 2022-05-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0004_alter_standincidence_checked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peticionstand',
            old_name='estado',
            new_name='concedido',
        ),
    ]
