# Generated by Django 4.0.3 on 2022-05-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0005_rename_estado_peticionstand_concedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('empresa_colaboradora', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeptAdditionalServ',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeticionServAdicional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('extra', models.BooleanField(default=False)),
                ('concedido', models.BooleanField(default=False)),
                ('clientUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente')),
                ('deptAdditionalServUsername', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.deptadditionalserv')),
                ('idAdditionalService', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.additionalservice')),
                ('idEvento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
                ('idStand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.stand')),
            ],
        ),
        migrations.CreateModel(
            name='PeticionEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=200)),
                ('adminUsername', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idEvento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
                ('organizerUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='ListaNegra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('clientUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente')),
                ('organizerUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciasServAdicional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('solucionado', models.BooleanField(default=False)),
                ('clientUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente')),
                ('deptAdditionalServUsername', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.deptadditionalserv')),
                ('idAdditionalService', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.additionalservice')),
                ('idEvento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.event')),
                ('idStand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.stand')),
            ],
        ),
    ]
