# Generated by Django 4.0.4 on 2022-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0005_distribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='Current_Event',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='Occupied',
        ),
        migrations.AddField(
            model_name='distribution',
            name='Occupied',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
