# Generated by Django 4.0.4 on 2022-04-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0006_remove_stand_current_event_remove_stand_occupied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Topic', models.CharField(choices=[('Stand request', 'Stand request'), ('Stand Incidence', 'Stand Incidence')], max_length=100)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='standrequest',
            name='Client_Username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsAndMore.cliente'),
        ),
    ]
