# Generated by Django 4.0.3 on 2022-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0007_additionalservice_habilitado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='is_deptAdditionalServ',
            field=models.BooleanField(default=False),
        ),
    ]
