# Generated by Django 4.0.3 on 2022-05-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0008_peticionservadicional_revisado_and_more'),
        ('EventsAndMore', '0008_webuser_is_deptadditionalserv'),
    ]

    operations = [
    ]
