# Generated by Django 4.0.3 on 2022-05-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsAndMore', '0008_webuser_is_deptadditionalserv_webuser_is_organizer'),
        ('EventsAndMore', '0010_remove_peticionevento_adminusername_and_more'),
    ]

    operations = [
    ]
